### ISSUE TITLE
no sampling rate info in SortingExtractor

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/spikeextractors#26]
If you save `SortingExtactor` without the raw data it cannot be read because `SortingExtractor.__init__` requires the acquisition to be present. This would be easy to fix if we implement https://github.com/NeurodataWithoutBorders/nwb-schema/issues/273. We could then pull the sampling rate information from the `Units` object instead of taking it from the acquisition `ElectricalSeries`.

**Comment by luiztauffer** [comment]
for now, the partial solution is `sampling_frequency` being passed as an optional argument to `NwbSortingExtractor`

**Comment by CodyCBakerPhD** [comment]
The current version works as follows

```
    def __init__(self, file_path, electrical_series=None, sampling_frequency=None):

            ...

            if sampling_frequency is None:
                # defines the electrical series from where the sorting came from
                # important to know the sampling_frequency
                if electrical_series is None:
                    if len(nwbfile.acquisition) > 1:
                        raise Exception('More than one acquisition found. You must specify electrical_series.')
                    if len(nwbfile.acquisition) == 0:
                        raise Exception('No acquisitions found in the .nwb file.')
                    es = list(nwbfile.acquisition.values())[0]
                else:
                    es = electrical_series
                # get rate
                if es.rate is not None:
                    self._sampling_frequency = es.rate
                else:
                    self._sampling_frequency = 1 / (es.timestamps[1] - es.timestamps[0])
            else:
                self._sampling_frequency = sampling_frequency
```

Does this resolve the issue or would you prefer something more sophisticated? I know a lot of other things have changed since last year as well.

**Comment by bendichter** [comment]
@CodyCBakerPhD we should use https://github.com/NeurodataWithoutBorders/nwb-schema/pull/328/files instead
