### ISSUE TITLE
build out and apply _check_sortings_equal

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/spikeextractors#27]
We should add `_check_sortings_equal` to the nwb test. Also, `_check_sortings_equal` currently does not test equality for many of the data types:

https://github.com/ben-dichter-consulting/spikeextractors/blob/86ab96d4467194c92e4af42ee1fa56be0e2064f1/tests/test_extractors.py#L302-L313

Let's build out to be a more rigorous test, similar to `_check_recordings_equal`:

https://github.com/ben-dichter-consulting/spikeextractors/blob/86ab96d4467194c92e4af42ee1fa56be0e2064f1/tests/test_extractors.py#L258-L292

**Comment by CodyCBakerPhD** [comment]
Though these functions have migrated to the utils of SpikeExtractors, their structure is largely the same as the version this issue was raised for. Is this still something you would eventually like to be improved?
