### ISSUE TITLE
channel info

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/spikeextractors#7]
Use `get_channel_groups`, `get_channel_property_names`, and `get_channel_properties` to write electrodes table on write and to read from electrodes table on read.

**Comment by luiztauffer** [comment]
@bendichter 
I believe we're doing this already, [here](https://github.com/ben-dichter-consulting/spikeextractors/blob/56bdb7e383c49468fad57a09f74371420b53cb7e/spikeextractors/extractors/nwbextractors/nwbextractors.py#L73) and [here](https://github.com/ben-dichter-consulting/spikeextractors/blob/56bdb7e383c49468fad57a09f74371420b53cb7e/spikeextractors/extractors/nwbextractors/nwbextractors.py#L93)

are you thinking on extending for `add_electrode_column()` for attributes other than `location`?

**Comment by bendichter** [comment]
Yes we should write all channel properties exposed by the extractor

**Comment by luiztauffer** [comment]
Done in **nwb** branch
